### ISSUE TITLE
Bug in the 3d euler roe solver fortran file?

### ISSUE THREAD

**Issue by selbsterklaerend** [clawpack/riemann#132]
Hello clawpackers.
I have a question concerning the Roe solver for ideal gas law. 
The fortran file i'm talking about is
https://github.com/clawpack/riemann/blob/master/src/rpn3_euler.f90
In lines 171 to 176 the wave amplitudes alpha(...) are calculated from the deltas (differences of the conservative left and right state vectors) and some Roe-averaged variables.
I made the effort to compare the alphas in the code to the alphas in the book of Toro (Riemann Solvers and Numerical Methods for Fluid Dynamics, 3rd ed, page 357, formulae (11.68/69). 
The alphas in the clawpack code seem to agree with Toro's alphas, except for alpha(5) in the code (which in Toro's book is named alpha_1, because the eigenvectors are numbered in a different order than in clawpack).
clawpack:
alpha(5) = ( delta(rho u) + (a-u)delta(rho) - a alpha(4)  ) / (2 a)

Toro:
alpha_1  = (-delta(rho u) + (a+u)delta(rho) - a alpha_2  ) / (2 a)
where Toro's alpha_2 is identical to clawpack's alpha(4) (i checked that). The rest of the alphas also agree (except for the numbering).
Numbering:
clawpack: alpha(1),alpha(2),alpha(3),alpha(4),alpha(5) correspond to respectively
Toro:     alpha_5, alpha_3 ,alpha_4 ,alpha_2 ,alpha_1
Except for the numbering, the eigenvectors seem to be the same in clawpack and Toro's book (i.e. there is no different scaling involved in the two sources). One can see this by comparing the factors after the alphas in the code lines 182-200 to Toro's formula (11.59) on page 356.
I checked Toro's formulae for the alphas (by elimination and so on ...), and i arrived exactly at Toro's results, so they seem right.
So i wonder if there's a bug in the clawpack code? Why does clawpack's alpha(5) not agree with Toros alpha_1 ? Did i get something wrong?
Thanks for your answers and comments.

**Comment by mandli** [comment]
I think your ordering of the vectors is not quite right.  The interesting values for these are all the same regardless of dimensionality so we can safely consider the 1D case.  From LeVeque [1] pg. 323 we get the 3 expressions found in the Clawpack solvers
```
alpha(2) = (gamma - 1) * ((gamma - 1) * ((H - u**2) * delta(1) + u * delta(2) - delta(3)) / c**2
alpha(3) = (delta(2) + (c - u) * delta(1) - c * alpha(2))) / (2 * c)
alpha(1) = delta(1) - alpha(2) - alpha(3)
```
where the `alpha(3)` expression is the troublesome one.  I believe that if you stick `alpha(3)` into the expression for `alpha(1)` we then come to the same form from Toro so they are in fact equivalent.

1.	LeVeque, R. Finite Volume Methods for Hyperbolic Problems. Cambridge University Press (Cambridge University Press, 2002).

**Comment by ketch** [comment]
What @mandli has observed is right -- in fact, the order of the eigenvectors in this Riemann solver is the same as the ordering of the eigenvectors in Toro's book.  This should be clear from comparing precisely the equations and code lines that you have referenced, @selbsterklaerend .

I'm going to close this issue.
